steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'frontend-repository', '--image', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', '--platform=managed', '--region=us-west1']